# Generated by Django 2.2.6 on 2020-08-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200828_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='submit',
        ),
    ]
