# Generated by Django 2.2.6 on 2020-08-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_option_submit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='options_text',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='question_text',
        ),
    ]
