# Generated by Django 2.2.6 on 2020-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200828_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
