# Generated by Django 2.2.6 on 2020-08-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200828_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Option'),
        ),
    ]
