# Generated by Django 2.2.6 on 2020-08-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='options',
            new_name='answer',
        ),
    ]
