# Generated by Django 2.2.6 on 2020-08-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200829_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_taker',
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
    ]
