# Generated by Django 2.2.6 on 2020-08-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200829_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
