# Generated by Django 2.2.6 on 2020-08-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200829_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
