# Generated by Django 2.2.6 on 2020-08-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20200831_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
    ]
